---
title: "Practice 11/5"
author: "Olly Gill"
date: "11/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(babynames)
library(infer)
library(moderndive)
library(skimr)
library(tidyverse)
```

```{r}
lm.obj <- lm(score ~ age + gender, data = evals)

get_regression_table(lm.obj)

bootstrap_distribution <- evals %>%
  specify(response = age) %>%
  generate(reps = 1000) %>%
  calculate(stat = "mean")
  
visualize(bootstrap_distribution)

percentile_ci <- bootstrap_distribution %>%
  get_confidence_interval(level = 0.95, type = "percentile")

percentile_ci
  
```

```{r}
evals %>%
  rep_sample_n(size = 463, replace = TRUE, reps = 10) %>%
  group_by(replicate) %>%
  summarize(mean_age = mean(age)) %>%
  summarize(lower = quantile(mean_age, prob = 0.025),
            middle = quantile(mean_age, prob = 0.5),
            higher = quantile(mean_age, prob = 0.975))
```

```{r}
evals %>%
  rep_sample_n(size = 463, replace = TRUE, reps = 10) %>%
  group_by(replicate) %>%
  nest() %>%
  mutate(results = map(data, ~ lm(score ~ age + gender, data = .x))) %>%
  mutate(coefficients = map(results, ~coef(.x))) %>%
  mutate(age_coef = map_dbl(coefficients, ~ pluck(.x, "age")))
```

